-- 숫자형 built-in 함수 --

SELECT ABS(-10) FROM DUAL;

SELECT CEIL(5.5) FROM DUAL;

SELECT FLOOR(5.5) FROM DUAL;

SELECT EXP(5) FROM DUAL;

SELECT LN(5) FROM DUAL;

SELECT LOG(10, 1000) FROM DUAL;

-- 17을 3으로 나눈 나머지를 반환
SELECT MOD(17, 3) FROM DUAL;

SELECT POWER(5,2) FROM DUAL;


SELECT SIGN(-19) FROM DUAL;

SELECT SQRT(25) FROM DUAL;

-- 말그래도 round
SELECT ROUND(3.545, 2) FROM DUAL;

-- round가 아닌 해당 자리에서 절사
SELECT TRUNCATE(3.545, 2) FROM DUAL;

-- 문자형 함수 --
SELECT CONCAT('A','B') FROM DUAL;

SELECT UPPER('sql') FROM DUAL;

SELECT LOWER('SQL') FROM DUAL;

SELECT LPAD('SQL', 5, '*') FROM DUAL;
SELECT RPAD('SQL', 5, '*') FROM DUAL;

SELECT SUBSTR('ABCDEFG', 1, 3) FROM DUAL;

-- 공백 제거
SELECT LTRIM('  SQL  ') FROM DUAL;
SELECT RTRIM('  SQL  ') FROM DUAL;

SELECT TRIM(' ABCD EFG ') FROM DUAL;
SELECT TRIM(LEADING FROM ' ABCD EFG ') FROM DUAL;
SELECT TRIM(LEADING 'AB' FROM 'ABCD EFG ') FROM DUAL;
SELECT TRIM(TRAILING 'FG ' FROM 'ABCD EFG ') FROM DUAL;

SELECT LENGTH('SQL') FROM DUAL;
SELECT CHAR_LENGTH('SQL') FROM DUAL;
SELECT CHAR_LENGTH('에스큐엘') FROM DUAL;
SELECT LENGTH('에스큐엘') FROM DUAL;

SELECT REPLACE('ABC', 'B', 'D') FROM DUAL;


-- 한글제거
SELECT REGEXP_REPLACE('ab12cd한글(테스트)','[가-힣]','') AS remove_digits;

-- 숫자제거 
SELECT REGEXP_REPLACE('ab12cd한글(테스트)','[0-9]','') AS remove_digits;

-- 영문제거
SELECT REGEXP_REPLACE('ab12cd한글(테스트)','[a-z]','') AS remove_digits;

-- 한글과 특수문자 ( ) 제거
SELECT REGEXP_REPLACE('ab12cd한글(테스트)','[가-힣()]','') AS remove_digits;






